### ISSUE TITLE
mead-load-build-dependencies script doesn't handle relocations

### ISSUE THREAD

**Issue by jdcasey** [sbadakhc/kojak#41]
relocation sources (the POM that specifies the relocation) aren't listed in Downloading... lines in the build.log. Therefore, they're ignored by the import script for koji.

Because the relocation was triggered during the build, this sets up the situation where the relocation source will still be referenced, but will never be available in koji.

The import script needs to search for relocation warnings and map them to Downloading... lines in order to grab the relocation-source POM and import it alongside the rest of the relocation target files.

**Comment by sbadakhc** [comment]
Solved with import-maven-repo
