### ISSUE TITLE
can't install kojak on machines with multipath disks

### ISSUE THREAD

**Issue by g0dd4rd** [sbadakhc/kojak#47]
The following error was found while parsing the kickstart configuration file:
The following problem occurred on line 5 of the kickstart file:
Specified nonexistent disk vda in ignoredisk command
install exited abnormally [1/1] 
The system will be rebooted when you press Ctrl-C or Ctrl-Alt-Delete.

kojak-ks.cfg:
#version=DEVEL
auth --enableshadow --passalgo=sha512
url --url http://mirror.centos.org/centos/6/os/x86_64/
firstboot --disable
ignoredisk --only-use=vda
lang en_US.UTF-8
keyboard us
network --hostname=koji.localdomain --bootproto=static --ip=192.168.122.2 --netmask=255.255.255.0 --gateway=192.168.122.1 --nameserver=192.168.122.1
rootpw --iscrypted $1$osxvII91$h0GUDy5ST6KMHKKX15ZFh.
selinux --disabled
firewall --disabled
timezone America/New_York --isUtc
skipx
bootloader --location=mbr --driveorder=vda --append="crashkernel=auto rhgb quiet"
autopart
zerombr
clearpart --all --initlabel --drives=vda
reboot

**Comment by sbadakhc** [comment]
Vda refers to a virtual disk.  In this instance it seems that those disks will need to be created before Kojak is run but with out having the hardware to test on I cannot be sure.  Closing for now but if you experience this again simply reopen the ticket and include messages, dmesg and any other log files.
