### ISSUE TITLE
create_vm script lists saved configs twice

### ISSUE THREAD

**Issue by g0dd4rd** [sbadakhc/kojak#48]
>> Select which configuration file you want to use.

1) /var/tmp/kojak/cfg/RedHat/CentOS/6.5/x86_64/kojak.cfg
2) /var/tmp/kojak/cfg/RedHat/CentOS/6/5/x86_64/kojak.cfg
3) Quit

-bash-4.1# ls -ltr /var/tmp/kojak/cfg/RedHat/CentOS/6.5/x86_64/
total 4
-rw-r--r-- 1 root root 355 Jul 15 20:22 kojak.cfg

**Comment by sbadakhc** [comment]
I cannot reproduce this.  Can you include the steps you took or verify that this is still an issue?

**Comment by sbadakhc** [comment]
Still not able to reproduce...Any updates?

**Comment by g0dd4rd** [comment]
Can't reproduce either. feel free to close this one please.
