### ISSUE TITLE
Vagrant fails to find VirtualBox

### ISSUE THREAD

**Issue by sbadakhc** [sbadakhc/kojak#55]
After the vagrant installation finishes I'm prompted to restart the system.  After the system has rebooted I re-execute the scripts and it tries to re-install Vagrant.  When I cancel the installation the script pick the installation back up but Vagrant complains that a vagrant file already exists.  After that Vagrant complains that it cannot find VirtualBox.

**Comment by g0dd4rd** [comment]
Where does this happen please, on Windows?

**Comment by sbadakhc** [comment]
Yes on Windows but I cannot reproduce it!  Closing.
