### ISSUE TITLE
Permission denied: '/mnt/koji/work/cli-import' on machine with SELinux enabled

### ISSUE THREAD

**Issue by msrb** [sbadakhc/kojak#64]
I can see following error message while performing local host installation on machine with SELinux enabled:

```
+ koji import --create-build /opt/kojak/pkgs/maven3-3.0.3-4.src.rpm /opt/kojak/pkgs/maven3-3.0.3-4.noarch.rpm
uploading /opt/kojak/pkgs/maven3-3.0.3-4.src.rpm... Fault: <Fault 1: "<type 'exceptions.OSError'>: [Errno 13] Permission denied: '/mnt/koji/work/cli-import'">
+ koji add-pkg --owner=kojiadmin CENTOS-6 maven3
+ koji tag-build CENTOS-6-candidate maven3-3.0.3-4
GenericError: No matching build found: maven3-3.0.3-4
```

As per [Koji/ServerHowTo], httpd should be allowed to modify files/directories labeled "public_content_rw_t":
```
# setsebool -P allow_httpd_anon_write=1
# chcon -R -t public_content_rw_t /mnt/koji/*
```

[Koji/ServerHowTo]: https://fedoraproject.org/wiki/Koji/ServerHowTo#SELinux_Configuration

**Comment by sbadakhc** [comment]
Thanks Michal,

I will update.

Cheers,
Sal.

----- Original Message -----

**Comment by sbadakhc** [comment]
Added check in configuration phase.
'''
# Check SELinux
STATUS=$(sestatus | grep enabled)
if [ -z $STATUS ]; then
    echo "off"
else
    echo -e "\n# Configuring SELinux Policiy"
    setsebool -P allow_httpd_anon_write=1
    chcon -R -t public_content_rw_t /mnt/koji/*
fi
'''
