### ISSUE TITLE
Script install/install fails because of missing netstat command

### ISSUE THREAD

**Issue by rudineirk** [sbadakhc/kojak#66]
The script don't install the package net-tools and fails at some point because the command netstat is missing.

Tested on CentOS 7 x64

**Comment by sbadakhc** [comment]
Thanks for the heads up.  Currently the scripts assumes installation on CentOS 6.  I will put in an OS test which will install net-tools for the time being until rpms are shipped out.

**Comment by sbadakhc** [comment]
Fixed in latest...please let me know how you get on before I close this.

https://github.com/sbadakhc/kojak/commit/c8bd6858e16acf9bc6d6c48ee604337b0d8c0c4c

**Comment by sbadakhc** [comment]
Assuming fixed.  Please re-open if this is still an issue for you.
