### ISSUE TITLE
Not necessary to install VirtualBox if it is already installed

### ISSUE THREAD

**Issue by tkdchen** [sbadakhc/kojak#68]
As the subject. I have installed VirtualBox in my Fedora 21, however kojak still downloads yum repo file and installs VirtualBox on behalf of me.

**Comment by sbadakhc** [comment]
Hi, Apologies for the late response.  I'm marking this under investigation!  Thanks for the heads up.

**Comment by sbadakhc** [comment]
Was your installation from source?  If it was an rpm installation this should not happen.

**Comment by tkdchen** [comment]
Yes. I tried it by following the steps in README, clone first and then issue `./kojak`.

**Comment by sbadakhc** [comment]
IIf VirtualBox was installed as an rpm then then the re-installation would be skipped as the binary would be identified as installed in the rpm database.  Can you provide an error message?

**Comment by sbadakhc** [comment]
Hi,

I will test this out later in week.  Apologies for the delay but I'm currently on deployment and wont be back for a few days.

**Comment by tkdchen** [comment]
There is no error message, kojak just continue to begin the installation of VirtualBox. Following is what I installed of VirtualBox.

```
$ rpm -aq | grep VirtualBox
VirtualBox-guest-4.3.26-1.fc21.x86_64
kmod-VirtualBox-3.19.4-200.fc21.x86_64-4.3.26-1.fc21.4.x86_64
kmod-VirtualBox-3.19.3-200.fc21.x86_64-4.3.26-1.fc21.3.x86_64
VirtualBox-4.3-4.3.26_98988_fedora18-1.x86_64
```

**Comment by sbadakhc** [comment]
Thanks for the patch!.
