### ISSUE TITLE
yum -y update breaks environments

### ISSUE THREAD

**Issue by g0dd4rd** [sbadakhc/kojak#74]
Description:
I wanted to install Kojak into VBox VM on my f21. The Create VM step failed due to unavailable / incompatible vboxdrv module with the updated kernel.
Steps to reproduce:
- git clone https://github.com/sbadakhc/kojak.git
- cd kojak; sudo ./kojak
- vm-shell: ./kojak
Expected results:
being in the vm shell, ready to issue ./kojak and do the actual installation
Actual results:
yum -y update . . .
. . .
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
=== version check ===
VBoxManage --version
WARNING: The vboxdrv kernel module is not loaded. Either there is no module
         available for the current kernel (3.19.4-200.fc21.x86_64) or it failed to
         load. Please recompile the kernel module and install it by

           sudo /etc/init.d/vboxdrv setup

         You will not be able to start VMs until this problem is fixed.
4.3.26_RPMFusionr98988
=== probing ===
modinfo vboxdrv
modinfo: ERROR: Module vboxdrv not found.

**Comment by sbadakhc** [comment]
I think I'm in love with this bug report!

**Comment by sbadakhc** [comment]
Sent to bug reports #69 and #74

**Comment by g0dd4rd** [comment]
We can use the commands from #76 to get rid of yum -y update

**Comment by sbadakhc** [comment]
I will just remove the yum -y update from the scripts.  Future installations wont run this.

**Comment by sbadakhc** [comment]
Ah I forgot to mention...following from our conversation I think we agreed to maintain a blacklist of applications instead of denying the update.

So in yum.conf we have entries like:

exclude=php* kernel*

**Comment by tkdchen** [comment]
Why need to `yum -y update` before create_vm?

**Comment by sbadakhc** [comment]
The short answer is that we don't need to :)  When started the Kojak project there were a number of dependencies which were in a very fast development cycle.  I was also workin on Fedora at the time and things like libvirtd caused of many problems.  I put the yum update in to to ensure I was in a good place before creating the VM.  Since the switch to CentOS I guess we can remove this.

**Comment by sbadakhc** [comment]
Removed.
