### ISSUE TITLE
/root/kojak/scripts/config/config: line 40: [: too many arguments

### ISSUE THREAD

**Issue by maxamillion** [sbadakhc/kojak#79]
After performing a local install using kojak, when I run the `configure` option it throws an error but appears to continue configuring.

```
################################################################################
#                                                                              #
#                    !!! Welcome to Kojak...Koji in a box !!!                  #
#                                                                              #

>> Select from the menu options below.

1) Create VM      3) Configure      5) Create Broker
2) Install        4) Uninstall      6) Quit
Please Select installation type: 3

>> Configuring System
/root/workspace/kojak/scripts/config/config: line 40: [: too many arguments

# Configuring SELinux Policiy

```
However looking at the script, I'm not entirely sure what the issue is and the configuration appears to complete cleanly but I wanted to be sure and report it.

**Comment by slmingol** [comment]
The issue with this section of code is as follows:

    # Check SELinux
    STATUS=$(sestatus | grep enabled)
    if [ -z "$STATUS" ]; then
        echo -e "\n# SELinux not enabled..."

The var `$STATUS` needs to be wrapped in double quotes since you're seeing if the result returned by the above grep returned a string of zero length or not.

**Comment by sbadakhc** [comment]
Great thanks and well spotted! I stuck it in curly braces to follow the existing conventions.
