### ISSUE TITLE
Post install the kojibuilder is "not ready"

### ISSUE THREAD

**Issue by maxamillion** [sbadakhc/kojak#81]
After a local install and configuration using kojak, the kojibuilder is listed as "Not Ready"

```
$ koji list-hosts
Hostname                     Enb Rdy Load/Cap Arches           Last Update
kojibuilder1                 Y   N    0.0/10.0 x86_64           2015-06-19 19:58:09
```

This is causing builds to never be scheduled and instead stay in the "free" state forever.

**Comment by maxamillion** [comment]
Any update on this? Any more information I could provide that might help in diagnosing?

**Comment by sbadakhc** [comment]
Aplogies Max, I have been on deployment and only just got back.  Please provide some more info.  In the meantime I will provision a fed22 vbox and attempt to reproduce.  BTW please check this bug also...https://github.com/sbadakhc/kojak/issues/83

**Comment by sbadakhc** [comment]
I can confirm that the workaround in bug #83 fixes things.  Can you confirm on your end?

**Comment by maxamillion** [comment]
confirmed, thanks!

**Comment by sbadakhc** [comment]
Great thanks!
